"use client";

import type { Page1KPIs } from "./types";
import KPICard from "./KPICard";

interface KPIGridProps {
  kpis: Page1KPIs;
}

const CARD_DEFINITIONS: Array<{
  key: keyof Page1KPIs;
  label: string;
  format: (kpis: Page1KPIs) => string;
  tooltip: string;
  trendKey: keyof Page1KPIs;
  improvementDirection: "higher" | "lower" | "none";
}> = [
  {
    key: "humanHoursSavedFormatted",
    label: "Est. Human Hours Saved",
    format: (k) => k.humanHoursSavedFormatted,
    tooltip: "Manual video editing time eliminated (1 raw hour = 3 hours editing).",
    trendKey: "humanHoursTrendPct",
    improvementDirection: "higher",
  },
  {
    key: "timeToMarketHours",
    label: "Time-to-Market / Production Velocity",
    format: (k) => `${k.timeToMarketHours}h`,
    tooltip: "Average time from raw upload to live on social media.",
    trendKey: "timeToMarketTrendPct",
    improvementDirection: "lower",
  },
  {
    key: "contentWasteFormatted",
    label: "Content Waste Index",
    format: (k) => k.contentWasteFormatted,
    tooltip: "Volume of content generated by the AI that is never used.",
    trendKey: "contentWasteTrendPct",
    improvementDirection: "lower",
  },
  {
    key: "clientConcentrationPct",
    label: "Client Concentration Risk",
    format: (k) => `${k.clientConcentrationPct}%`,
    tooltip: "Percentage of total platform usage from the biggest client.",
    trendKey: "clientConcentrationTrendPct",
    improvementDirection: "lower",
  },
  {
    key: "totalUploadedCount",
    label: "Total Uploaded Volume",
    format: (k) => `${k.totalUploadedCount.toLocaleString()} (${k.totalUploadedDurationFormatted})`,
    tooltip: "Raw amount of long-form and live content entering the system.",
    trendKey: "totalUploadedTrendPct",
    improvementDirection: "higher",
  },
  {
    key: "totalCreated",
    label: "Total AI-Generated Output",
    format: (k) => k.totalCreated.toLocaleString(),
    tooltip: "Total short-form videos, chapters, and summaries created.",
    trendKey: "totalCreatedTrendPct",
    improvementDirection: "higher",
  },
  {
    key: "aiContentMultiplier",
    label: "AI Content Multiplier",
    format: (k) => `${k.aiContentMultiplier}x`,
    tooltip: "How much manual work the AI is saving (e.g., 1 upload yields 8 assets).",
    trendKey: "aiMultiplierTrendPct",
    improvementDirection: "higher",
  },
  {
    key: "periodOverPeriodGrowthPct",
    label: "Period-over-Period Growth (Δ%)",
    format: (k) => `${k.periodOverPeriodGrowthPct >= 0 ? "+" : ""}${k.periodOverPeriodGrowthPct}%`,
    tooltip: "Growth or decline in adoption vs last period.",
    trendKey: "periodOverPeriodGrowthPct",
    improvementDirection: "none",
  },
  {
    key: "topPerformingOutputType",
    label: "Top Performing Output Type",
    format: (k) => k.topPerformingOutputType,
    tooltip: "The specific category driving the highest publish volume.",
    trendKey: "topPerformingOutputType",
    improvementDirection: "none",
  },
];

export default function KPIGrid({ kpis }: KPIGridProps) {
  return (
    <div className="rounded-xl border border-gray-200 bg-gray-50/50 p-3">
      <h4 className="text-[10px] font-bold uppercase tracking-wider text-gray-400 mb-3 flex items-center gap-2">
        Executive Vital Signs
        <span className="flex-1 h-px bg-gray-100" />
      </h4>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        {CARD_DEFINITIONS.map((def) => {
          const trendVal =
            def.improvementDirection !== "none"
              ? (kpis[def.trendKey] as number)
              : null;
          return (
            <KPICard
              key={def.key}
              label={def.label}
              value={def.format(kpis)}
              tooltip={def.tooltip}
              trendPct={typeof trendVal === "number" ? trendVal : null}
              improvementDirection={def.improvementDirection}
            />
          );
        })}
      </div>
    </div>
  );
}
